import { blogPostType } from "@/types/type";

export const blogs: blogPostType[] = [
  {
    id: 1,
    title: "The Future of AI: How Technology is Transforming Our Lives",
    author: "Sophia Johnson",
    tag: "Technology",
    date: "October 15, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/ai-future.jpg",
    mainImage: "/assets/ai-future.jpg",
    context:
      "AI is revolutionizing various industries and changing the way we interact with technology. From healthcare advancements to autonomous vehicles, explore the profound impact AI has on modern life.",
  },
  {
    id: 2,
    title: "Cybersecurity Essentials: Protecting Your Digital World",
    author: "David Lee",
    tag: "Technology",
    date: "October 20, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/cybersecurity.jpg",
    mainImage: "/assets/cybersecurity.jpg",
    context:
      "In an era of increased digital connectivity, protecting your personal and professional data is crucial. Learn essential tips to safeguard your online presence from cyber threats.",
  },
  {
    id: 3,
    title: "The Rise of Smart Homes: Technology for a Smarter Living",
    author: "Anna Williams",
    tag: "Technology",
    date: "October 25, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/smart-home.jpg",
    mainImage: "/assets/smart-home.jpg",
    context:
      "Smart home technology is making everyday living more convenient and efficient. Discover how smart devices are transforming homes and lifestyles with automation and innovation.",
  },
  {
    id: 4,
    title: "Blockchain Beyond Bitcoin: Revolutionizing Various Industries",
    author: "John Smith",
    tag: "Technology",
    date: "October 30, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/blockchain.jpg",
    mainImage: "/assets/blockchain.jpg",
    context:
      "Blockchain technology extends far beyond cryptocurrencies. Explore how it’s reshaping industries like finance, supply chain management, healthcare, and more.",
  },
  {
    id: 5,
    title: "How 5G Technology is Shaping the Future of Communication",
    author: "Mark Thompson",
    tag: "Technology",
    date: "November 5, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/5g-technology.jpg",
    mainImage: "/assets/5g-technology.jpg",
    context:
      "5G is revolutionizing communication with faster speeds and greater connectivity. Learn about its potential to change industries and everyday life.",
  },
  {
    id: 6,
    title: "Exploring the Advancements in Augmented Reality and VR",
    author: "Sarah Brown",
    tag: "Technology",
    date: "November 10, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/vr-ar.jpg",
    mainImage: "/assets/vr-ar.jpg",
    context:
      "AR and VR are opening new doors in entertainment, education, and beyond. Discover the latest advancements and their real-world applications.",
  },
  {
    id: 7,
    title: "Mindful Living: How Small Changes Can Lead to a Happier Life",
    author: "Emily White",
    tag: "Lifestyle",
    date: "October 15, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/mindful-living.png",
    mainImage: "/assets/mindful-living.png",
    context:
      "Adopting mindfulness practices can bring positive changes to your life. Discover simple steps to achieve a balanced and joyful lifestyle.",
  },
  {
    id: 8,
    title: "The Power of Minimalism: Declutter Your Life for Inner Peace",
    author: "Jack Taylor",
    tag: "Lifestyle",
    date: "October 20, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/minimalism.jpg",
    mainImage: "/assets/minimalism.jpg",
    context:
      "Embracing minimalism can lead to greater clarity and peace of mind. Learn how to declutter your surroundings and simplify your life.",
  },
  {
    id: 9,
    title: "The Role of Nutrition in Achieving a Balanced Lifestyle",
    author: "Laura Wilson",
    tag: "Lifestyle",
    date: "October 25, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/nutrition.jpg",
    mainImage: "/assets/nutrition.jpg",
    context:
      "Good nutrition is the foundation of a healthy lifestyle. Explore the importance of balanced eating and its impact on your overall well-being.",
  },
  {
    id: 10,
    title: "Exercise for the Mind: How Physical Activity Boosts Mental Health",
    author: "James Scott",
    tag: "Lifestyle",
    date: "October 30, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/exercise.jpg",
    mainImage: "/assets/exercise.jpg",
    context:
      "Physical activity is not just for the body but also the mind. Discover the mental health benefits of regular exercise and movement.",
  },
  {
    id: 11,
    title: "Time Management Hacks for a Productive and Fulfilling Life",
    author: "Grace Turner",
    tag: "Lifestyle",
    date: "November 5, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/time-management.jpg",
    mainImage: "/assets/time-management.jpg",
    context:
      "Managing time effectively can lead to greater productivity and satisfaction. Learn valuable hacks to organize your life and maximize your days.",
  },
  {
    id: 12,
    title: "Digital Detox: The Benefits of Disconnecting from Technology",
    author: "Olivia Davis",
    tag: "Lifestyle",
    date: "November 10, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/digital-detox.jpg",
    mainImage: "/assets/digital-detox.jpg",
    context:
      "Taking a break from technology can have profound effects on your mental health. Explore the benefits of a digital detox and how to implement it.",
  },
  {
    id: 13,
    title: "Discovering Hidden Gems: Off-the-Beaten-Path Travel Destinations",
    author: "Liam Carter",
    tag: "Travel",
    date: "October 15, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/hidden-gems.jpg",
    mainImage: "/assets/hidden-gems.jpg",
    context:
      "Travel beyond the typical tourist spots and explore hidden gems around the world. Get inspired to venture off the beaten path for unique experiences.",
  },
  {
    id: 14,
    title: "The Ultimate Travel Packing Guide: Essentials You Need",
    author: "Ella Green",
    tag: "Travel",
    date: "October 20, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/packing-guide.jpg",
    mainImage: "/assets/packing-guide.jpg",
    context:
      "Packing smart can make or break your travel experience. Learn essential tips to pack efficiently and travel with ease.",
  },
  {
    id: 15,
    title: "Solo Travel: Empowering Yourself Through Adventures",
    author: "Henry Allen",
    tag: "Travel",
    date: "October 25, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/solo-travel.jpg",
    mainImage: "/assets/solo-travel.jpg",
    context:
      "Solo travel offers unique opportunities for self-discovery and growth. Explore the joys and challenges of traveling alone and gain valuable insights.",
  },
  {
    id: 16,
    title: "Budget Travel Tips: Exploring the World Without Breaking the Bank",
    author: "Emma Harris",
    tag: "Travel",
    date: "October 30, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/budget-travel.jpg",
    mainImage: "/assets/budget-travel.jpg",
    context:
      "Traveling on a budget doesn’t mean compromising on experiences. Discover tips and tricks to explore the world without overspending.",
  },
  {
    id: 17,
    title: "Sustainable Travel: How to Be an Eco-Conscious Traveler",
    author: "Lucas Hill",
    tag: "Travel",
    date: "November 5, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/sustainable-travel.jpg",
    mainImage: "/assets/sustainable-travel.jpg",
    context:
      "Travel with a conscience by adopting sustainable practices. Learn how to minimize your environmental impact while exploring the world.",
  },
  {
    id: 18,
    title: "Travel Photography: Capturing Memories on Your Journey",
    author: "Mia Wright",
    tag: "Travel",
    date: "November 10, 2024",
    profile: "/assets/person.png",
    thumbnail: "/assets/travel-photography.jpg",
    mainImage: "/assets/travel-photography.jpg",
    context:
      "Travel photography allows you to capture and cherish memories from your journeys. Discover tips and techniques for stunning travel photos.",
  },
];
